version: '2'
services:
  logger:
    image: fluent/fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./logs/fluentd:/fluentd/log

  redis:
    image: redis
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data

  db-misc:
   image: mariadb
   env_file: ./envfiles/db-misc.env
   volumes:
     - ./data/db-misc:/var/lib/mysql
     - ./conf/mysql/conf.d:/etc/mysql/conf.d
#   ports:
#     - "13306:3306"

  ruboty-tsukuba:
    image: cnosuke/ruboty
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    env_file: ./envfiles/ruboty-tsukuba.env
    links:
      - redis:redis

  ruboty-sotomuki:
    image: cnosuke/ruboty
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    env_file: ./envfiles/ruboty-sotomuki.env
    links:
      - redis:redis

  rproxy:
    image: nginx
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/socks:/tmp/socks
    links:
      - rundeck
      - ame
      - funho
      - drone

  lgtm:
    image: cnosuke/lgtm
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    env_file: ./envfiles/lgtm.env
    volumes:
      - ./data/nginx/socks:/tmp/socks

  cnzo:
    image: cnosuke/cnzo
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    env_file: ./envfiles/cnzo.env
    volumes:
      - ./data/nginx/socks:/tmp/socks

  ame:
    image: cnosuke/tokyo_amage
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  rundeck:
    image: cnosuke/rundeck
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    env_file: ./envfiles/rundeck.env
    volumes:
      - ./conf/rundeck/realm:/etc/rundeck/realm
    links:
      - db-misc

  funho:
    image: cnosuke/funho
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    env_file: ./envfiles/funho.env
    volumes:
      - ./data/nginx/socks:/tmp/socks
    links:
      - db-misc

  vpn:
    image: cnosuke/softether
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    volumes:
      - ./conf/softether/vpn_server.config:/usr/local/vpnserver/vpn_server.config
    network_mode: host

  drone:
    image: drone/drone:0.4
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    volumes:
      - ./data/drone:/var/lib/drone
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./envfiles/drone.env
